"""Parse self-checks per Act (sequence, size, sentence-start) rendered as data/processed/parse_report.md."""

from dataclasses import dataclass, field
from itertools import pairwise

from backend.app.config import ActSpec, Settings
from backend.app.ingestion.parse import num_key
from backend.app.models import LegalChunk


@dataclass(frozen=True)
class SequenceIssues:
    """Problems in the order of section/article numbers."""

    gaps: list[str] = field(default_factory=list)
    duplicates: list[str] = field(default_factory=list)
    out_of_order: list[str] = field(default_factory=list)


@dataclass(frozen=True)
class ActReport:
    """Counts and flagged chunk ids for one Act."""

    name: str
    slug: str
    total: int = 0
    schedules: int = 0
    repealed: int = 0
    short: list[str] = field(default_factory=list)
    long: list[str] = field(default_factory=list)
    mid_sentence: list[str] = field(default_factory=list)
    empty: list[str] = field(default_factory=list)
    issues: SequenceIssues = field(default_factory=SequenceIssues)
    notes: list[str] = field(default_factory=list)

    @property
    def failed(self) -> bool:
        """An Act that produced no chunks fails the build."""
        return self.total == 0

    @classmethod
    def empty_for(cls, spec: ActSpec, note: str) -> "ActReport":
        """Report for an Act that was not parsed at all."""
        return cls(name=spec.name, slug=spec.slug, notes=[note])


def sequence_issues(nums: list[str]) -> SequenceIssues:
    """Gaps, duplicates and backward steps in document-order section numbers (41 < 41A < 42)."""
    gaps, out_of_order = [], []
    for prev, cur in pairwise(nums):
        prev_key, cur_key = num_key(prev), num_key(cur)
        if cur_key < prev_key:
            out_of_order.append(f"{prev} -> {cur}")
        elif cur_key[0] > prev_key[0] + 1:
            first, last = prev_key[0] + 1, cur_key[0] - 1
            gaps.append(f"{prev} -> {cur} (missing {first}{'' if first == last else f'-{last}'})")
    duplicates = sorted({n for n in nums if nums.count(n) > 1}, key=num_key)
    return SequenceIssues(gaps, duplicates, out_of_order)


def act_report(
    spec: ActSpec, chunks: list[LegalChunk], settings: Settings, notes: list[str] | None = None
) -> ActReport:
    """Self-checks for one Act's chunks."""
    live = [c for c in chunks if not c.repealed]
    return ActReport(
        name=spec.name,
        slug=spec.slug,
        total=len(chunks),
        schedules=sum(c.unit_type == "schedule" for c in chunks),
        repealed=len(chunks) - len(live),
        short=[c.chunk_id for c in live if len(c.text.split()) < settings.chunk_min_words],
        long=[c.chunk_id for c in chunks if len(c.text.split()) > settings.chunk_max_words],
        mid_sentence=[c.chunk_id for c in live if c.text[:1].islower()],
        empty=[c.chunk_id for c in chunks if not c.text.strip()],
        issues=sequence_issues([c.section_num for c in chunks if c.unit_type != "schedule"]),
        notes=notes or [],
    )


def _detail(label: str, items: list[str]) -> list[str]:
    return [f"- {label} ({len(items)}): {', '.join(items)}"] if items else []


def render_report(reports: list[ActReport]) -> str:
    """Markdown report: summary table, then flagged items per Act. No timestamps (deterministic)."""
    lines = [
        "# Parse report",
        "Generated by `python -m backend.app.ingestion.build_corpus`. Review with `scripts/inspect_chunks.py`.",
        "",
        "| Act | chunks | schedules | repealed | short | long | mid-sentence | gaps | duplicates | out-of-order |",
        "|---|---|---|---|---|---|---|---|---|---|",
    ]
    for r in reports:
        counts = [r.total, r.schedules, r.repealed, len(r.short), len(r.long), len(r.mid_sentence)]
        counts += [len(r.issues.gaps), len(r.issues.duplicates), len(r.issues.out_of_order)]
        lines.append(f"| {r.name} | {' | '.join(str(n) for n in counts)} |")
    for r in reports:
        lines += ["", f"## {r.name} (`{r.slug}`)"]
        lines += ["- **EMPTY PARSE**"] if r.failed else []
        lines += [f"- note: {note}" for note in r.notes]
        lines += _detail("gaps", r.issues.gaps) + _detail("duplicates", r.issues.duplicates)
        lines += _detail("out of order", r.issues.out_of_order) + _detail("empty", r.empty)
        lines += _detail("short (< min words, not repealed)", r.short) + _detail("long (> max words)", r.long)
        lines += _detail("starts mid-sentence", r.mid_sentence)
    return "\n".join(lines) + "\n"
