"""Background answer runs (D24) and per-sign-in notifications for GET /api/events.

A background run is generated by a server task, not by the SSE response, so it survives the client leaving. Its events
are kept in a RunBuffer that any number of stream connections can follow from the start. When the run ends, the
EventHub tells the sign-in that asked (turn_done / turn_failed); events nobody is listening for wait in a short backlog.
"""

import asyncio
from collections import deque
from collections.abc import AsyncGenerator, Mapping

from sse_starlette import ServerSentEvent

from backend.app.stream import sse


class RunBuffer:
    """The events of one background run so far; follow() replays them and then waits for more until finish()."""

    def __init__(self) -> None:
        self.events: list[ServerSentEvent] = []
        self.finished = False
        self.task: asyncio.Task[None] | None = None
        self._changed = asyncio.Event()

    def push(self, event: ServerSentEvent) -> None:
        """Append an event and wake the followers."""
        self.events.append(event)
        self._wake()

    def finish(self) -> None:
        """No more events (idempotent); followers end after the last one."""
        self.finished = True
        self._wake()

    def _wake(self) -> None:
        self._changed.set()
        self._changed = asyncio.Event()

    async def follow(self) -> AsyncGenerator[ServerSentEvent, None]:
        """Every event from the first, then each new one as it arrives, ending when the run has finished."""
        sent = 0
        while True:
            while sent < len(self.events):
                yield self.events[sent]
                sent += 1
            if self.finished:
                return
            await self._changed.wait()


class EventHub:
    """Notification queues per sign-in (token hash); each connected GET /api/events has its own queue."""

    def __init__(self, backlog: int) -> None:
        self._backlog_size = backlog
        self._listeners: dict[str, set[asyncio.Queue[ServerSentEvent]]] = {}
        self._backlog: dict[str, deque[ServerSentEvent]] = {}

    def publish(self, key: str, name: str, data: Mapping[str, object]) -> None:
        """Send an event to every connection of that sign-in, or keep it until one connects."""
        event = sse(name, data)
        listeners = self._listeners.get(key)
        if listeners:
            for queue in listeners:
                queue.put_nowait(event)
            return
        self._backlog.setdefault(key, deque(maxlen=self._backlog_size)).append(event)

    async def subscribe(self, key: str) -> AsyncGenerator[ServerSentEvent, None]:
        """The sign-in's events: the waiting backlog first, then live ones, until the client disconnects."""
        queue: asyncio.Queue[ServerSentEvent] = asyncio.Queue()
        for event in self._backlog.pop(key, ()):
            queue.put_nowait(event)
        self._listeners.setdefault(key, set()).add(queue)
        try:
            while True:
                yield await queue.get()
        finally:
            listeners = self._listeners.get(key, set())
            listeners.discard(queue)
            if not listeners:
                self._listeners.pop(key, None)

    def listening(self, key: str) -> int:
        """Connected /api/events streams of a sign-in."""
        return len(self._listeners.get(key, ()))
